# Generated by Django 3.1 on 2023-12-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='Variation',
        ),
    ]
