databases:
  - name: greatcartdb
    plan: free
    databaseName: greatcart
    user: greatcart

services:
  - type: web
    plan: free
    name: greatcart
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn greatkart.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: greatcartdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4